stages:
  - check
  - build 

check:
  stage: check
  image: alpine/curl
  before_script:
    - apk add jq
  script:
    - echo "REMOTE_VER=$(curl https://api.github.com/repos/usnistgov/oscal-cli/tags | jq '.[0].name' | sed 's/\"v\(.*\)\"/\1/g')" >> build.env
    - echo "LOCAL_VER=$(curl -L gitlab.com/api/v4/projects/38819444/registry/repositories/3360380/tags| jq '.[0].name' | sed 's/\"\(.*\)\"/\1/g'" >> build.env
  artifacts:
    reports:
      dotenv: build.env
      
build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$REMOTE_VER --build-arg RELEASE=$REMOTE_VER .
    - docker push $CI_REGISTRY_IMAGE:$REMOTE_VER
  rules:
    - if: $REMOTE_VER != $LOCAL_VER
  dependencies:
    - check