query:
  image: alpine/curl
  before_script:
    - apk add jq
  script:
    - echo "RELEASE=$(curl https://api.github.com/repos/usnistgov/oscal-cli/tags | jq '.[0].name')" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build:
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE --build-arg RELEASE=$RELEASE .
    - docker push $CI_REGISTRY_IMAGE:$RELEASE
  dependencies:
    - query
